# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178B3yrXARgEHwp0g868ls4RmZO5n8j8H
"""

import pandas as pd

import matplotlib.pyplot as plt

df = pd.read_csv('//content/Project/consumer_type_sales.csv')


# basic info and statistics
print(df.info())
print(df.describe())

# divide by customer type and sum the Total Sales
sales_by_customer = df.groupby("customer type")["Total_Sales"].sum()

# bar chart
plt.figure(figsize=(8, 5))
sales_by_customer.plot(kind="bar", color=["blue", "green"])
plt.title("Total Sales by Customer Type")
plt.xlabel("Customer Type")
plt.ylabel("Total Sales")
plt.xticks(rotation=0)
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()
