# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178B3yrXARgEHwp0g868ls4RmZO5n8j8H
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('//content/Project/monthly_sales.csv')
df

# basic info and statistics
print(df.info())
print(df.describe())

# time series chart for Total Sales
df['Date'] = pd.to_datetime(df[['Year', 'Month']].assign(DAY=1))
df.set_index('Date', inplace=True)

plt.figure(figsize=(10, 6))
plt.plot(df.index, df['Total_Sales'], marker='o', color='blue', linestyle='-', linewidth=2)

# title and labels
plt.title("Monthly Sales Time Series")
plt.xlabel("Date")
plt.ylabel("Total Sales")
plt.grid(True, linestyle="--", alpha=0.7)

plt.show()

