# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178B3yrXARgEHwp0g868ls4RmZO5n8j8H
"""

import pandas as pd

df = pd.read_csv('/content/Project/paymen_method_count.csv')

import matplotlib.pyplot as plt

# general info about the data
print(df.info())

# summary statistics
print(df.describe())

# Group by Payment method and sum the Payment Count
payment_counts = df.groupby("Payment")["Payment_Count"].sum()

#  bar chart
payment_counts.plot(kind="bar", color=["blue", "green", "red"])
plt.title("Payment Method Distribution")
plt.xlabel("Payment Method")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.7)
plt.show()