# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/178B3yrXARgEHwp0g868ls4RmZO5n8j8H
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file
df = pd.read_csv('/content/Project/product_line_prices.csv')
df

# basic info and statistics
print(df.info())
print(df.describe())

# bar chart
df.set_index('Product line')[['Min_Price', 'Max_Price', 'Avg_Price']].plot(kind='bar', width=0.8)

plt.title("Price Comparison for Different Product Lines")
plt.xlabel("Product Line")
plt.ylabel("Price")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.7)

plt.tight_layout()
plt.show()

